parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  jest/globals: true
plugins:
- react-hooks
- jest
extends:
- plugin:react/recommended
- plugin:@typescript-eslint/recommended
- prettier/@typescript-eslint
- plugin:prettier/recommended
- prettier/react
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  react/jsx-filename-extension:
  - 1
  - extensions:
    - ".js"
    - ".ts"
    - ".tsx"
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-var-requires": off
  "@typescript-eslint/explicit-module-boundary-types": off
  react/prop-types: 0
settings:
  react:
    version: detect