export { IndexContainerStyle as IndexContainer } from './style'
export { SectionVisionStyle as SectionVision } from './style'
export { SectionAnnounceStyle as SectionAnnounce } from './style'
export { SectionServiceStyle as SectionService } from './style'
export { SectionPartnerShipStyle as SectionPartnerShip } from './style'
